version: "3"
networks:
  default:
    external: true
    name: npm_default
services:
  drawio:
    stdin_open: true
    tty: true
    container_name: draw
    # ports:
    #   - 8080:8080
    #   - 8443:8443
    image: jgraph/drawio
    environment:
      KEYSTORE_PASS: ${KEYSTORE_PASS}
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.18