version: "3"
networks:
  default:
    external: true
    name: npm_default
services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    environment:
      ADMINER_PLUGINS: sql-log
      ADMINER_DESIGN: flat
      ADMINER_DEFAULT_SERVER: myql8
    networks:
      default:
        ipv4_address: 172.20.0.11