version: "3"
networks:
  default:
    external: true
    name: npm_default
services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA}/adguardhome/work:/opt/adguardhome/work
      - ${DOCKER_DATA}/adguardhome/conf:/opt/adguardhome/conf
      - ${DOCKER_DATA}/NPM/letsencrypt/archive:/opt/adguardhome/archive
    image: adguard/adguardhome
    # ports:
    #   - 8080:8080
    networks:
      default:
        ipv4_address: 172.20.0.14
