version: "3"
networks:
  default:
    external: true
    name: npm_default
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    volumes:
      - ${DOCKER_DATA}/alist/data:/opt/alist/data
    # ports:
    #   - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
    networks:
      default: